import type { Essential, EssentialFilterOption } from "./types"

export const ESSENTIALS: Essential[] = [
  {
    id: 1,
    title: "Utiliser un gestionnaire de mots de passe",
    description: "Un gestionnaire génère et stocke des mots de passe uniques pour chaque site. Fini les post-its.",
    importance: "Critique",
    category: "motsdepasse",
    type: "Guide",
    difficulty: "Facile",
    os: ["Tous"],
    popularity: 92,
    details:
      "Bitwarden (gratuit, open source) ou 1Password permettent de stocker tous vos mots de passe chiffrés. Vous ne retenez plus qu'un seul mot de passe maître. Plus jamais de réutilisation risquée.",
    icon: "key",
  },
  {
    id: 2,
    title: "Activer la double authentification (2FA)",
    description: "Même si votre mot de passe est volé, la 2FA bloque l'accès à votre compte.",
    importance: "Critique",
    category: "motsdepasse",
    type: "Réglage",
    difficulty: "Facile",
    os: ["Tous"],
    popularity: 88,
    details:
      "Activez la 2FA sur vos comptes mail, banque, réseaux sociaux. Préférez une application (Aegis, Authy, Google Authenticator) plutôt que les SMS, beaucoup moins sécurisés (SIM swapping).",
    icon: "shield",
  },
  {
    id: 3,
    title: "Mettre à jour ses appareils régulièrement",
    description: "Les mises à jour ferment les portes ouvertes que les pirates exploitent.",
    importance: "Critique",
    category: "appareils",
    type: "Réglage",
    difficulty: "Facile",
    os: ["Windows", "macOS", "Mobile"],
    popularity: 85,
    details:
      "Activez les mises à jour automatiques sur Windows, macOS, Android et iOS. Mettez aussi à jour vos navigateurs et extensions. Un appareil non mis à jour est une porte ouverte.",
    icon: "hard-drive",
  },
  {
    id: 4,
    title: "Sauvegarder ses données (règle 3-2-1)",
    description: "Une assurance vie numérique en cas de panne, vol ou ransomware.",
    importance: "Critique",
    category: "donnees",
    type: "Habitude",
    difficulty: "Moyen",
    os: ["Tous"],
    popularity: 78,
    details:
      "3 copies de vos données, sur 2 supports différents (disque externe + cloud), dont 1 hors site. OneDrive, Google Drive, iCloud sont de bonnes options. Pour les puristes : un NAS ou Backblaze.",
    icon: "save",
  },
  {
    id: 5,
    title: "Repérer les emails de phishing",
    description: "Le phishing est l'arnaque numéro 1. Apprenez à reconnaître les signaux.",
    importance: "Critique",
    category: "phishing",
    type: "Notion",
    difficulty: "Facile",
    os: ["Tous"],
    popularity: 95,
    details:
      "Vérifiez l'expéditeur (le vrai, pas seulement le nom affiché), survolez les liens pour voir l'URL réelle, méfiez-vous des urgences artificielles (« compte suspendu », « facture impayée »), ne donnez jamais vos identifiants par mail.",
    icon: "mail",
  },
  {
    id: 6,
    title: "Sécuriser son Wi-Fi à la maison",
    description: "WPA3 ou WPA2-AES, mot de passe fort, nom de réseau neutre.",
    importance: "Important",
    category: "wifi",
    type: "Réglage",
    difficulty: "Moyen",
    os: ["Tous"],
    popularity: 72,
    details:
      "Connectez-vous à l'admin de votre box. Activez WPA3 si dispo (sinon WPA2-AES). Changez le mot de passe Wi-Fi par défaut. Désactivez WPS. Renommez le SSID sans mentionner votre nom ou votre opérateur.",
    icon: "wifi",
  },
  {
    id: 7,
    title: "Verrouiller automatiquement son écran",
    description: "Configurez un verrouillage rapide pour bloquer les regards indiscrets.",
    importance: "Important",
    category: "appareils",
    type: "Réglage",
    difficulty: "Facile",
    os: ["Windows", "macOS", "Mobile"],
    popularity: 68,
    details:
      "Réglez le verrouillage automatique entre 1 et 5 minutes. Sur Windows : Win+L. Sur macOS : Ctrl+Cmd+Q. Sur mobile : verrouillage par biométrie ou code de 6 chiffres minimum.",
    icon: "lock",
  },
  {
    id: 8,
    title: "Maîtriser ses paramètres de confidentialité",
    description: "Les réseaux sociaux, navigateurs et OS partagent par défaut beaucoup trop.",
    importance: "Important",
    category: "donnees",
    type: "Réglage",
    difficulty: "Moyen",
    os: ["Tous"],
    popularity: 64,
    details:
      "Faites le tour des paramètres confidentialité de Facebook, Instagram, TikTok, X, votre navigateur et votre OS. Désactivez le suivi publicitaire, limitez la visibilité de vos publications, révoquez les apps inutiles.",
    icon: "eye",
  },
  {
    id: 9,
    title: "Protéger son téléphone mobile",
    description: "Le smartphone est devenu la cible principale. Verrouillage, sources, autorisations.",
    importance: "Important",
    category: "appareils",
    type: "Guide",
    difficulty: "Facile",
    os: ["Mobile"],
    popularity: 81,
    details:
      "Verrouillage biométrique + code 6 chiffres. N'installez que depuis le store officiel. Vérifiez les autorisations des apps (micro, position, contacts). Activez le chiffrement et la localisation à distance.",
    icon: "smartphone",
  },
  {
    id: 10,
    title: "Choisir un mot de passe maître robuste",
    description: "La phrase de passe : longue, mémorable, difficile à deviner.",
    importance: "Critique",
    category: "motsdepasse",
    type: "Notion",
    difficulty: "Facile",
    os: ["Tous"],
    popularity: 90,
    details:
      "Préférez une phrase de passe (4-6 mots aléatoires) à un mot de passe court avec des symboles. Exemple : « cheval-banane-tortue-vélo ». Ne réutilisez jamais ce mot de passe ailleurs.",
    icon: "key",
  },
  {
    id: 11,
    title: "Utiliser un cloud chiffré",
    description: "Vos fichiers sont-ils accessibles à votre fournisseur ?",
    importance: "Recommandé",
    category: "donnees",
    type: "Guide",
    difficulty: "Moyen",
    os: ["Tous"],
    popularity: 55,
    details:
      "Pour des données sensibles, préférez un cloud chiffré de bout en bout : Proton Drive, Tresorit, Cryptomator par-dessus un cloud classique. Vos fichiers ne peuvent être lus que par vous.",
    icon: "cloud",
  },
  {
    id: 12,
    title: "Identifier les arnaques par téléphone",
    description: "Le « faux conseiller bancaire » et le SMS de livraison restent très courants.",
    importance: "Important",
    category: "phishing",
    type: "Notion",
    difficulty: "Facile",
    os: ["Tous"],
    popularity: 76,
    details:
      "Ne donnez jamais vos codes de carte ou identifiants par téléphone. Si on vous appelle de votre banque, raccrochez et rappelez le numéro officiel. Méfiez-vous des SMS « colis bloqué » avec un lien.",
    icon: "mail",
  },
]

export const ESSENTIAL_FILTER_OPTIONS: Record<
  "priority" | "os" | "difficulty" | "type",
  EssentialFilterOption[]
> = {
  priority: [
    { id: "all", label: "Toutes" },
    { id: "Critique", label: "Priorité absolue" },
    { id: "Important", label: "Important" },
    { id: "Recommandé", label: "Recommandé" },
  ],
  os: [
    { id: "all", label: "Tous OS" },
    { id: "Windows", label: "Windows" },
    { id: "macOS", label: "macOS" },
    { id: "Mobile", label: "Mobile" },
  ],
  difficulty: [
    { id: "all", label: "Toute difficulté" },
    { id: "Facile", label: "Facile" },
    { id: "Moyen", label: "Moyen" },
    { id: "Avancé", label: "Avancé" },
  ],
  type: [
    { id: "all", label: "Tout type" },
    { id: "Guide", label: "Guides" },
    { id: "Réglage", label: "Réglages" },
    { id: "Habitude", label: "Habitudes" },
    { id: "Notion", label: "Notions" },
  ],
}
